# frozen_string_literal: true

require "fileutils"
require "json"
require "yaml"

require_relative "../quality/coverage_parser"
require_relative "../quality/coverage_snapshot"
require_relative "../quality/flog_parser"
require_relative "../quality/rubocop_parser"
require_relative "../quality/report"

QUALITY_DIR = Rails.root.join("tmp/quality")

namespace :quality do
  task :setup do
    FileUtils.mkdir_p(QUALITY_DIR)
  end

  desc "Run Rubocop metrics and parse results"
  task rubocop: :setup do
    json_path = QUALITY_DIR.join("rubocop.json")
    cops = %w[
      Metrics/ClassLength
      Metrics/ModuleLength
      Metrics/MethodLength
      Metrics/AbcSize
      Metrics/CyclomaticComplexity
      Metrics/PerceivedComplexity
    ].join(",")

    sh "bundle exec rubocop --format json --only #{cops} > #{json_path} 2>&1 || true"

    parser = Quality::RubocopParser.new(json_path)
    result = parser.parse
    File.write(QUALITY_DIR.join("rubocop_metrics.json"), JSON.pretty_generate(result))
  end

  desc "Run Flog and parse results"
  task flog: :setup do
    parser = Quality::FlogParser.new(%w[app lib/quality])
    result = parser.parse
    File.write(QUALITY_DIR.join("flog.json"), JSON.pretty_generate(result))
  end
end

desc "Run all quality gates"
task quality: "quality:setup" do
  Rake::Task["quality:rubocop"].invoke
  Rake::Task["quality:flog"].invoke

  measurements = {}

  # Coverage (generated by test task via SimpleCov)
  coverage_path = Quality::CoverageSnapshot.preferred_path(Rails.root)
  if coverage_path.exist?
    measurements[:coverage] = Quality::CoverageParser.new(coverage_path).parse
  end

  # Rubocop
  rubocop_path = QUALITY_DIR.join("rubocop_metrics.json")
  if rubocop_path.exist?
    measurements.merge!(JSON.parse(File.read(rubocop_path), symbolize_names: true))
  end

  # Flog
  flog_path = QUALITY_DIR.join("flog.json")
  if flog_path.exist?
    measurements[:flog] = JSON.parse(File.read(flog_path), symbolize_names: true)
  end

  thresholds = YAML.load_file(Rails.root.join("config/quality_thresholds.yml"))
  report = Quality::Report.new(measurements: measurements, thresholds: thresholds)

  puts report
  exit(report.passed? ? 0 : 1)
end
