services:
  rails:
    image: ghcr.io/stadia/ra-news:latest
    container_name: rails
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_LOG_LEVEL=info
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_ENV=production

      - WEB_CONCURRENCY=2
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - IMAP_ADDRESS=${IMAP_ADDRESS}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - WEB_PUSH_VAPID_PUBLIC_KEY=${WEB_PUSH_VAPID_PUBLIC_KEY}
      - WEB_PUSH_VAPID_PRIVATE_KEY=${WEB_PUSH_VAPID_PRIVATE_KEY}
      - WEB_PUSH_VAPID_SUBJECT=${WEB_PUSH_VAPID_SUBJECT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.news.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.ruby-https.redirectscheme.scheme=https"
      - "traefik.http.routers.ruby-http.entrypoints=web"
      - "traefik.http.routers.ruby-http.middlewares=ruby-https"
      - "traefik.http.routers.ruby-http.rule=Host(`ruby-news.kr`) || Host(`www.ruby-news.kr`)"
      - "traefik.http.routers.ruby.entrypoints=websecure"
      - "traefik.http.routers.ruby.rule=Host(`ruby-news.kr`) || Host(`www.ruby-news.kr`)"
      - "traefik.http.routers.ruby.tls.certresolver=letsencrypt"
    networks:
      - homeNetwork
    restart: unless-stopped
    volumes:
      - news_data:/rails/public/sitemaps
      - news_data:/rails/storage

  solid-queue:
    image: ghcr.io/stadia/ra-news:latest
    container_name: solid-queue
    command: bin/jobs
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_LOG_LEVEL=info
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_ENV=production

      - WEB_CONCURRENCY=2
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - IMAP_ADDRESS=${IMAP_ADDRESS}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - WEB_PUSH_VAPID_PUBLIC_KEY=${WEB_PUSH_VAPID_PUBLIC_KEY}
      - WEB_PUSH_VAPID_PRIVATE_KEY=${WEB_PUSH_VAPID_PRIVATE_KEY}
      - WEB_PUSH_VAPID_SUBJECT=${WEB_PUSH_VAPID_SUBJECT}
    networks:
      - homeNetwork
    restart: unless-stopped
    volumes:
      - news_data:/rails/public/sitemaps
      - news_data:/rails/storage

  scrapling:
    image: pyd4vinci/scrapling:latest
    container_name: scrapling
    command: mcp --http
    networks:
      - homeNetwork
    restart: unless-stopped

  chrome:
    image: browserless/chrome:latest
    container_name: chrome
    networks:
      - homeNetwork
    restart: unless-stopped

networks:
  homeNetwork:
    external: true

volumes:
  news_data:
    external: true
