coverage:
  line_min: 75.0
  branch_min: 55.0
flog:
  method_max: 93
  class_max: 289
rubocop_metrics:
  class_length_max: 100
  method_length_max: 15
  abc_size_max: 15
  cyclomatic_complexity_max: 6
  perceived_complexity_max: 7
